package nucleo

import (
	"encoding/json"
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"
	"unicode/utf8"
)

// The wire format between the app and the harness (§3.3). It is used on the fd-4 and fd-3 pipes and
// in the memory files. The harness side is generated by arenero and must agree with this exactly.
//
//	CInt, CRune, CByte  integer number
//	CFloat              number; NaN → "NaN", +Inf → "+Inf", −Inf → "-Inf"
//	CBool               true / false
//	CString             JSON string if valid UTF-8, otherwise {"b64":"…"} (standard base64 with padding, RFC 4648 §4)
//	CLista              null (nil) or array
//	CArreglo            array of exactly Largo
//	CMapa               null or array of [k, v] pairs sorted by Comparar(k)
//	CStruct             array of field values in declaration order
//	CPuntero            null or the struct encoding
//	CError              null or {"error":"message"}
//
// Floats are written with strconv.FormatFloat(f, 'g', -1, 64); strings escape only '"', '\\', control
// characters, U+2028 and U+2029 (no HTML escaping).

// CodificarJSON encodes v (canonical dynamic form) as type t.
func CodificarJSON(v Valor, t Tipo) (json.RawMessage, error) {
	var sb strings.Builder
	if err := codificar(&sb, v, t, 0); err != nil {
		return nil, err
	}
	return json.RawMessage(sb.String()), nil
}

func codificar(sb *strings.Builder, v Valor, t Tipo, prof int) error {
	if prof > maxProfundidad {
		return errProfundo
	}
	switch t.Clase {
	case CInt, CRune, CByte:
		i, ok := comoEntero(v)
		if !ok {
			return errCodificar(v, t)
		}
		sb.WriteString(strconv.FormatInt(i, 10))
	case CFloat:
		f, ok := comoFloat(v)
		if !ok {
			return errCodificar(v, t)
		}
		switch {
		case math.IsNaN(f):
			sb.WriteString(`"NaN"`)
		case math.IsInf(f, 1):
			sb.WriteString(`"+Inf"`)
		case math.IsInf(f, -1):
			sb.WriteString(`"-Inf"`)
		default:
			sb.WriteString(strconv.FormatFloat(f, 'g', -1, 64))
		}
	case CBool:
		b, ok := v.(bool)
		if !ok {
			return errCodificar(v, t)
		}
		sb.WriteString(strconv.FormatBool(b))
	case CString:
		s, ok := v.(string)
		if !ok {
			return errCodificar(v, t)
		}
		if utf8.ValidString(s) {
			escribirCadenaJSON(sb, s)
		} else {
			sb.WriteString(`{"b64":"`)
			sb.WriteString(base64Codificar([]byte(s)))
			sb.WriteString(`"}`)
		}
	case CError:
		switch x := v.(type) {
		case nil:
			sb.WriteString("null")
		case ErrorV:
			sb.WriteString(`{"error":`)
			escribirCadenaJSON(sb, strings.ToValidUTF8(string(x), "�"))
			sb.WriteString("}")
		default:
			return errCodificar(v, t)
		}
	case CLista, CArreglo:
		if v == nil && t.Clase == CLista {
			sb.WriteString("null")
			return nil
		}
		xs, ok := v.([]Valor)
		if !ok {
			return errCodificar(v, t)
		}
		if xs == nil && t.Clase == CLista {
			sb.WriteString("null")
			return nil
		}
		if t.Clase == CArreglo && len(xs) != t.Largo {
			return fmt.Errorf("codificar %s: hay %d elementos y deben ser %d", t.Go(), len(xs), t.Largo)
		}
		e := elemDe(t.Elem)
		sb.WriteByte('[')
		for i, x := range xs {
			if i > 0 {
				sb.WriteByte(',')
			}
			if err := codificar(sb, x, e, prof+1); err != nil {
				return err
			}
		}
		sb.WriteByte(']')
	case CMapa:
		if v == nil {
			sb.WriteString("null")
			return nil
		}
		m, ok := v.(Mapa)
		if !ok {
			return errCodificar(v, t)
		}
		if m == nil {
			sb.WriteString("null")
			return nil
		}
		k, e := elemDe(t.Clave), elemDe(t.Elem)
		orden := make(Mapa, len(m))
		copy(orden, m)
		sort.SliceStable(orden, func(i, j int) bool { return Comparar(orden[i].K, orden[j].K) < 0 })
		sb.WriteByte('[')
		for i, p := range orden {
			if i > 0 {
				sb.WriteByte(',')
			}
			sb.WriteByte('[')
			if err := codificar(sb, p.K, k, prof+1); err != nil {
				return err
			}
			sb.WriteByte(',')
			if err := codificar(sb, p.V, e, prof+1); err != nil {
				return err
			}
			sb.WriteByte(']')
		}
		sb.WriteByte(']')
	case CStruct:
		s, ok := v.(Estructura)
		if !ok {
			return errCodificar(v, t)
		}
		if len(s) != len(t.Campos) {
			return fmt.Errorf("codificar %s: hay %d campos y deben ser %d", t.Go(), len(s), len(t.Campos))
		}
		sb.WriteByte('[')
		for i, x := range s {
			if i > 0 {
				sb.WriteByte(',')
			}
			if err := codificar(sb, x, t.Campos[i].Tipo, prof+1); err != nil {
				return err
			}
		}
		sb.WriteByte(']')
	case CPuntero:
		if v == nil {
			sb.WriteString("null")
			return nil
		}
		return codificar(sb, v, elemDe(t.Elem), prof+1)
	default:
		return fmt.Errorf("codificar: el tipo %s no se puede codificar", t.Go())
	}
	return nil
}

func errCodificar(v Valor, t Tipo) error {
	return fmt.Errorf("codificar: el valor %s (%T) no es de tipo %s", recortar(fmt.Sprint(v)), v, t.Go())
}

const hexDigitos = "0123456789abcdef"

// escribirCadenaJSON writes s (valid UTF-8) as a JSON string without HTML escaping.
func escribirCadenaJSON(sb *strings.Builder, s string) {
	sb.WriteByte('"')
	for _, r := range s {
		switch {
		case r == '"':
			sb.WriteString(`\"`)
		case r == '\\':
			sb.WriteString(`\\`)
		case r == '\n':
			sb.WriteString(`\n`)
		case r == '\r':
			sb.WriteString(`\r`)
		case r == '\t':
			sb.WriteString(`\t`)
		case r < 0x20:
			sb.WriteString(`\u00`)
			sb.WriteByte(hexDigitos[r>>4])
			sb.WriteByte(hexDigitos[r&0xF])
		case r == ' ':
			sb.WriteString(` `)
		case r == ' ':
			sb.WriteString(` `)
		default:
			sb.WriteRune(r)
		}
	}
	sb.WriteByte('"')
}

// DecodificarJSON decodes m as type t. It uses json.Decoder.UseNumber; ints are parsed with strconv.ParseInt.
func DecodificarJSON(m json.RawMessage, t Tipo) (Valor, error) {
	dec := json.NewDecoder(strings.NewReader(string(m)))
	dec.UseNumber()
	var x any
	if err := dec.Decode(&x); err != nil {
		return nil, fmt.Errorf("decodificar %s: %v", t.Go(), err)
	}
	if dec.More() {
		return nil, fmt.Errorf("decodificar %s: sobra texto después del valor", t.Go())
	}
	return desdeJSON(x, t, 0)
}

func errDecodificar(x any, t Tipo) error {
	return fmt.Errorf("decodificar: %s no es un valor de tipo %s", recortar(fmt.Sprint(x)), t.Go())
}

func desdeJSON(x any, t Tipo, prof int) (Valor, error) {
	if prof > maxProfundidad {
		return nil, errProfundo
	}
	switch t.Clase {
	case CInt, CRune, CByte:
		n, ok := x.(json.Number)
		if !ok {
			return nil, errDecodificar(x, t)
		}
		i, err := strconv.ParseInt(string(n), 10, 64)
		if err != nil {
			return nil, fmt.Errorf("decodificar %s: %q no es un entero de 64 bits", t.Go(), string(n))
		}
		return ajustarEntero(i, t)
	case CFloat:
		switch y := x.(type) {
		case json.Number:
			f, err := strconv.ParseFloat(string(y), 64)
			if err != nil {
				return nil, fmt.Errorf("decodificar %s: %q no es un número", t.Go(), string(y))
			}
			return redondearFloat(f, t), nil
		case string:
			switch y {
			case "NaN":
				return math.NaN(), nil
			case "+Inf", "Inf":
				return math.Inf(1), nil
			case "-Inf":
				return math.Inf(-1), nil
			}
		}
		return nil, errDecodificar(x, t)
	case CBool:
		b, ok := x.(bool)
		if !ok {
			return nil, errDecodificar(x, t)
		}
		return b, nil
	case CString:
		switch y := x.(type) {
		case string:
			return y, nil
		case map[string]any:
			if s, ok := y["b64"].(string); ok && len(y) == 1 {
				b, err := base64Decodificar(s)
				if err != nil {
					return nil, fmt.Errorf("decodificar string: %v", err)
				}
				return string(b), nil
			}
		}
		return nil, errDecodificar(x, t)
	case CError:
		switch y := x.(type) {
		case nil:
			return nil, nil
		case map[string]any:
			if s, ok := y["error"].(string); ok {
				return ErrorV(s), nil
			}
		}
		return nil, errDecodificar(x, t)
	case CLista, CArreglo:
		if x == nil {
			if t.Clase == CLista {
				return []Valor(nil), nil
			}
			return nil, fmt.Errorf("decodificar %s: un arreglo no puede ser null", t.Go())
		}
		xs, ok := x.([]any)
		if !ok {
			return nil, errDecodificar(x, t)
		}
		if t.Clase == CArreglo && len(xs) != t.Largo {
			return nil, fmt.Errorf("decodificar %s: hay %d elementos y deben ser %d", t.Go(), len(xs), t.Largo)
		}
		e := elemDe(t.Elem)
		out := make([]Valor, len(xs))
		for i, y := range xs {
			v, err := desdeJSON(y, e, prof+1)
			if err != nil {
				return nil, err
			}
			out[i] = v
		}
		return out, nil
	case CMapa:
		if x == nil {
			return Mapa(nil), nil
		}
		xs, ok := x.([]any)
		if !ok {
			return nil, errDecodificar(x, t)
		}
		k, e := elemDe(t.Clave), elemDe(t.Elem)
		out := make(Mapa, 0, len(xs))
		for _, y := range xs {
			par, ok := y.([]any)
			if !ok || len(par) != 2 {
				return nil, fmt.Errorf("decodificar %s: cada entrada debe ser [clave, valor]", t.Go())
			}
			kv, err := desdeJSON(par[0], k, prof+1)
			if err != nil {
				return nil, err
			}
			vv, err := desdeJSON(par[1], e, prof+1)
			if err != nil {
				return nil, err
			}
			out = append(out, Par{K: kv, V: vv})
		}
		return out.Ordenada(), nil
	case CStruct:
		xs, ok := x.([]any)
		if !ok {
			return nil, errDecodificar(x, t)
		}
		if len(xs) != len(t.Campos) {
			return nil, fmt.Errorf("decodificar %s: hay %d campos y deben ser %d", t.Go(), len(xs), len(t.Campos))
		}
		out := make(Estructura, len(xs))
		for i, y := range xs {
			v, err := desdeJSON(y, t.Campos[i].Tipo, prof+1)
			if err != nil {
				return nil, err
			}
			out[i] = v
		}
		return out, nil
	case CPuntero:
		if x == nil {
			return nil, nil
		}
		return desdeJSON(x, elemDe(t.Elem), prof+1)
	}
	return nil, fmt.Errorf("decodificar: el tipo %s no se puede decodificar", t.Go())
}

// ---- base64 (standard alphabet, with padding; encoding/base64 is outside nucleo's import list) ----

const alfabeto64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"

func base64Codificar(b []byte) string {
	var sb strings.Builder
	sb.Grow((len(b) + 2) / 3 * 4)
	for i := 0; i < len(b); i += 3 {
		var n uint32
		resto := len(b) - i
		n = uint32(b[i]) << 16
		if resto > 1 {
			n |= uint32(b[i+1]) << 8
		}
		if resto > 2 {
			n |= uint32(b[i+2])
		}
		sb.WriteByte(alfabeto64[n>>18&63])
		sb.WriteByte(alfabeto64[n>>12&63])
		if resto > 1 {
			sb.WriteByte(alfabeto64[n>>6&63])
		} else {
			sb.WriteByte('=')
		}
		if resto > 2 {
			sb.WriteByte(alfabeto64[n&63])
		} else {
			sb.WriteByte('=')
		}
	}
	return sb.String()
}

func base64Decodificar(s string) ([]byte, error) {
	if len(s)%4 != 0 {
		return nil, fmt.Errorf("base64: longitud %d no es múltiplo de 4", len(s))
	}
	out := make([]byte, 0, len(s)/4*3)
	for i := 0; i < len(s); i += 4 {
		var n uint32
		relleno := 0
		for j := 0; j < 4; j++ {
			c := s[i+j]
			var d int
			if c == '=' {
				if i+4 != len(s) || j < 2 {
					return nil, fmt.Errorf("base64: «=» fuera de lugar")
				}
				relleno++
				d = 0
			} else {
				if relleno > 0 {
					return nil, fmt.Errorf("base64: datos después de «=»")
				}
				d = strings.IndexByte(alfabeto64, c)
				if d < 0 {
					return nil, fmt.Errorf("base64: carácter no válido %q", c)
				}
			}
			n = n<<6 | uint32(d)
		}
		out = append(out, byte(n>>16))
		if relleno < 2 {
			out = append(out, byte(n>>8))
		}
		if relleno < 1 {
			out = append(out, byte(n))
		}
	}
	return out, nil
}

// ---- persisted cases ----

// CasoGuardado is a case persisted in memory files: entries/expectations encoded with the codec above.
type CasoGuardado struct {
	Entradas    []json.RawMessage `json:"e"`
	Esperado    []json.RawMessage `json:"r,omitempty"`
	Expectativa Expectativa       `json:"x,omitempty"`
	Origen      Origen            `json:"o"`
	Nota        string            `json:"n,omitempty"`
}

// GuardarCasos encodes cases of signature f (inputs as f.Entradas(), expected values as f.Res).
func GuardarCasos(f Firma, cs []Caso) ([]CasoGuardado, error) {
	ent := f.Entradas()
	out := make([]CasoGuardado, 0, len(cs))
	for n, c := range cs {
		if len(c.Entradas) != len(ent) {
			return nil, fmt.Errorf("caso %d: tiene %d entradas y %s necesita %d", n+1, len(c.Entradas), f.Nombre, len(ent))
		}
		g := CasoGuardado{Expectativa: c.Expectativa, Origen: c.Origen, Nota: c.Nota}
		g.Entradas = make([]json.RawMessage, len(ent))
		for i, t := range ent {
			m, err := CodificarJSON(c.Entradas[i], t)
			if err != nil {
				return nil, fmt.Errorf("caso %d, entrada %d: %w", n+1, i+1, err)
			}
			g.Entradas[i] = m
		}
		if c.Esperado != nil {
			if len(c.Esperado) != len(f.Res) {
				return nil, fmt.Errorf("caso %d: tiene %d resultados esperados y %s devuelve %d", n+1, len(c.Esperado), f.Nombre, len(f.Res))
			}
			g.Esperado = make([]json.RawMessage, len(f.Res))
			for i, t := range f.Res {
				m, err := CodificarJSON(c.Esperado[i], t)
				if err != nil {
					return nil, fmt.Errorf("caso %d, resultado %d: %w", n+1, i+1, err)
				}
				g.Esperado[i] = m
			}
		}
		out = append(out, g)
	}
	return out, nil
}

// LeerCasos decodes cases saved by GuardarCasos.
func LeerCasos(f Firma, gs []CasoGuardado) ([]Caso, error) {
	ent := f.Entradas()
	out := make([]Caso, 0, len(gs))
	for n, g := range gs {
		if len(g.Entradas) != len(ent) {
			return nil, fmt.Errorf("caso %d: tiene %d entradas y %s necesita %d", n+1, len(g.Entradas), f.Nombre, len(ent))
		}
		c := Caso{Expectativa: g.Expectativa, Origen: g.Origen, Nota: g.Nota}
		c.Entradas = make([]Valor, len(ent))
		for i, t := range ent {
			v, err := DecodificarJSON(g.Entradas[i], t)
			if err != nil {
				return nil, fmt.Errorf("caso %d, entrada %d: %w", n+1, i+1, err)
			}
			c.Entradas[i] = v
		}
		if g.Esperado != nil {
			if len(g.Esperado) != len(f.Res) {
				return nil, fmt.Errorf("caso %d: tiene %d resultados esperados y %s devuelve %d", n+1, len(g.Esperado), f.Nombre, len(f.Res))
			}
			c.Esperado = make([]Valor, len(f.Res))
			for i, t := range f.Res {
				v, err := DecodificarJSON(g.Esperado[i], t)
				if err != nil {
					return nil, fmt.Errorf("caso %d, resultado %d: %w", n+1, i+1, err)
				}
				c.Esperado[i] = v
			}
		}
		out = append(out, c)
	}
	return out, nil
}
